artifacts:
  root_dir: artifact

ingredient_picker:

  no_of_classes: 2
  trained_model_path: ckpt_best.pth
  save_image_dir_name: crop_images
  save_image_file_name: crop_image.jpg

upsampling_img:

  model_path: ESRGAN/models/RRDB_ESRGAN_x4.pth
  upsample_image_dir_name: upsample_images
  upsample_image_file_name: up.jpg




